version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"


  logstash:
    build: logstash/
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


  kibana:
    build: kibana/
    ports:
      - "8080:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


  fluentd:
    build: docker-fluentd/
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/:/var/lib/docker/
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    privileged: yes
