version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"


  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "8080:5601"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch


  fluentd:
    build: docker-fluentd/
    depends_on:
      - elasticsearch
    volumes:
      - /var/lib/docker/:/var/lib/docker/
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    privileged: yes
